/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectingImpactRouteImport } from './routes/connecting-impact'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PnrRouteImport } from './routes/pnr'
import { Route as StationCodeRouteImport } from './routes/station.$code'
import { Route as TrainNumberRouteImport } from './routes/train.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectingImpactRoute = ConnectingImpactRouteImport.update({
  id: '/connecting-impact',
  path: '/connecting-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PnrRoute = PnrRouteImport.update({
  id: '/pnr',
  path: '/pnr',
  getParentRoute: () => rootRouteImport,
} as any)
const StationCodeRoute = StationCodeRouteImport.update({
  id: '/station/$code',
  path: '/station/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainNumberRoute = TrainNumberRouteImport.update({
  id: '/train/$number',
  path: '/train/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connecting-impact': typeof ConnectingImpactRoute
  '/control-room': typeof ControlRoomRoute
  '/developer': typeof DeveloperRoute
  '/network': typeof NetworkRoute
  '/pnr': typeof PnrRoute
  '/station/$code': typeof StationCodeRoute
  '/train/$number': typeof TrainNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connecting-impact': typeof ConnectingImpactRoute
  '/control-room': typeof ControlRoomRoute
  '/developer': typeof DeveloperRoute
  '/network': typeof NetworkRoute
  '/pnr': typeof PnrRoute
  '/station/$code': typeof StationCodeRoute
  '/train/$number': typeof TrainNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connecting-impact': typeof ConnectingImpactRoute
  '/control-room': typeof ControlRoomRoute
  '/developer': typeof DeveloperRoute
  '/network': typeof NetworkRoute
  '/pnr': typeof PnrRoute
  '/station/$code': typeof StationCodeRoute
  '/train/$number': typeof TrainNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connecting-impact'
    | '/control-room'
    | '/developer'
    | '/network'
    | '/pnr'
    | '/station/$code'
    | '/train/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connecting-impact'
    | '/control-room'
    | '/developer'
    | '/network'
    | '/pnr'
    | '/station/$code'
    | '/train/$number'
  id:
    | '__root__'
    | '/'
    | '/connecting-impact'
    | '/control-room'
    | '/developer'
    | '/network'
    | '/pnr'
    | '/station/$code'
    | '/train/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectingImpactRoute: typeof ConnectingImpactRoute
  ControlRoomRoute: typeof ControlRoomRoute
  DeveloperRoute: typeof DeveloperRoute
  NetworkRoute: typeof NetworkRoute
  PnrRoute: typeof PnrRoute
  StationCodeRoute: typeof StationCodeRoute
  TrainNumberRoute: typeof TrainNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connecting-impact': {
      id: '/connecting-impact'
      path: '/connecting-impact'
      fullPath: '/connecting-impact'
      preLoaderRoute: typeof ConnectingImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnr': {
      id: '/pnr'
      path: '/pnr'
      fullPath: '/pnr'
      preLoaderRoute: typeof PnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$code': {
      id: '/station/$code'
      path: '/station/$code'
      fullPath: '/station/$code'
      preLoaderRoute: typeof StationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$number': {
      id: '/train/$number'
      path: '/train/$number'
      fullPath: '/train/$number'
      preLoaderRoute: typeof TrainNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectingImpactRoute: ConnectingImpactRoute,
  ControlRoomRoute: ControlRoomRoute,
  DeveloperRoute: DeveloperRoute,
  NetworkRoute: NetworkRoute,
  PnrRoute: PnrRoute,
  StationCodeRoute: StationCodeRoute,
  TrainNumberRoute: TrainNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
